/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include <stdint.h>
#include <stdio.h>
#include <math.h>
#include <string.h>  // Add this for memcpy
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxPort.h"
#include "IfxStm.h"
#include "tfthw.h"
#include "conio_tft.h"
#include "conio_cfg.h"
#include "conio_cfg.h"
#include "tft_app.h"
#include "Blinky_LED.h"
#include "Stm_Scheduler.h"
#include "IfxStm.h"
#include "prediction_data/predicted_vs_expected_all_params_4000_profile60_DenseMLP.h"
#include "prediction_data/input_features_4000_profile60.h"
#include "nn_models/densemlp/DenseMLP.simplified.h"
#include "nn_models/rnn/rnn.simplified.h"
#include "nn_models/tcn/tcn.simplified.h"
#include "graph_tft.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define TFT_BACKLIGHT_PORT  (&MODULE_P15)
#define TFT_BACKLIGHT_PIN    0   /* P15.0 – Backlight (active high) */
#define STM_PTR &MODULE_STM0
#define TEMP_SCALE 100
#define TCN_WINDOW_SIZE 64

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;
App_Cpu g_AppCpu0;  /* CPU 0 global data */
AppStm g_AppStm0;  /* STM 0 global data */
IFX_EXTERN volatile boolean tft_ready;

/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
IFX_INTERRUPT(userIsrSTM0, 0, ISR_PRIORITY_OS_TICK);

static void turnOnBacklight(void);
static void delayMs(uint32_t ms);
static inline uint64 now(void);
// Change this to switch models: uncomment the desired model
#define USE_MLP_MODEL
#define MLP_GRAPH
//#define USE_RNN_MODEL
//#define USE_TCN_MODEL
//#define COMPARE_PREDICTED

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
static void turnOnBacklight(void)
{
    IfxPort_setPinMode(TFT_BACKLIGHT_PORT, TFT_BACKLIGHT_PIN, IfxPort_Mode_outputPushPullGeneral);
    IfxPort_setPinHigh(TFT_BACKLIGHT_PORT, TFT_BACKLIGHT_PIN);
}

static void delayMs(uint32_t ms)
{
    IfxStm_waitTicks(&MODULE_STM0,
    IfxStm_getTicksFromMilliseconds(&MODULE_STM0, ms));
}

static inline uint64 now(void)
{
    return IfxStm_get(STM_PTR);
}

static inline float elapsed(Ifx_TickTime start)
{
    Ifx_TickTime end = IfxStm_get(STM_PTR);
    float32 freq = IfxStm_getFrequency(STM_PTR);
    return (float)(end - start) / freq * 1000.0f;  // milliseconds
}

void core0_main(void)
{
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    /* Cpu sync event wait, we wait until all CPUs are in corex_main to avoid initialization problems of variables */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    IfxCpu_enableInterrupts();

    initLED();  /* Initialize the LED port pin      */
    turnOnBacklight();
    tft_app_init((IfxCpu_ResourceCpu)IfxCpu_getCoreIndex());
    initStm(&g_AppStm0, (IfxCpu_ResourceCpu)IfxCpu_getCoreIndex());
    delayMs(1000); //Wait for Infineon Logo

    //***************************Code Start************************************//
    while (1)
    {
        /* Loop forever */
        display_graphics_clrscr(DISPLAYGRAPHICS0);
        display_ascii_printfxy (DISPLAYBAR, 0, 18, (const uint8 *)"Azlan Ikram Project Thesis AURIX TC-387");
        conio_driver.displaymode = DISPLAYSTDOUT0;
        display_ascii_printfxy (DISPLAYSTDOUT0, 0, 0, (const uint8 *)"-Electric Motor Temperature Estimation-");
        delayMs(5000);
        display_ascii_clrscr(DISPLAYSTDOUT0);

        volatile Ifx_TickTime start; /* Variables to measure elapsed time (in ticks)*/
        volatile Ifx_TickTime start_single_run; /* Variables to measure elapsed time (in ticks)*/
        volatile float latency = 0;
        volatile float latency_single_run = 0;
        volatile float avg_latency = 0;  // Add average latency tracking
        char buf[16];
        //        **********************DENSE MLP INFERENCE TESTING CODE STARTS HERE***********************

        #ifdef USE_MLP_MODEL
            display_ascii_printfxy (DISPLAYSTDOUT0, 10, 10, (const uint8 *)"RUNNING MLP MODEL ...");
            float input[1][1][10];
            float hidden_state[1][4] = {{0.5,0.5,0.5,0.5}};
            // Initialize hidden state with input values
            hidden_state[0][0] = expected[0][0] / TEMP_SCALE;
            hidden_state[0][1] = expected[0][1] / TEMP_SCALE;
            hidden_state[0][2] = expected[0][2] / TEMP_SCALE;
            hidden_state[0][3] = expected[0][3] / TEMP_SCALE;
            float output[1][4];
            float hidden_state_upd[1][1][4];

        #elif defined(USE_RNN_MODEL)
            display_ascii_printfxy (DISPLAYSTDOUT0, 10, 10, (const uint8 *)"RUNNING RNN MODEL ...");
            float input[1][1][14] = {{{1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0}}};
            float hidden_state[1][1][16] = {{{1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0}}};
            float cell_state[1][1][16] = {{{1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0}}};
            float output[1][4];
            // For RNN, initialize the input with the first data point
            input[0][0][INPUT_NUM_PARAMS] = expected[0][0] / TEMP_SCALE;  // PM
            input[0][0][INPUT_NUM_PARAMS + 1] = expected[0][1] / TEMP_SCALE;  // Stator Yoke
            input[0][0][INPUT_NUM_PARAMS + 2] = expected[0][2] / TEMP_SCALE;  // Stator Tooth
            input[0][0][INPUT_NUM_PARAMS + 3] = expected[0][3] / TEMP_SCALE;  // Stator Winding
        
        #elif defined(USE_TCN_MODEL)
            display_ascii_printfxy (DISPLAYSTDOUT0, 10, 10, (const uint8 *)"RUNNING TCN MODEL ...");
            float input[1][14][64] = {
                {
                    {1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0},
                    {1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0},
                    {1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0},
                    {1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0},
                    {1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0},
                    {1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0},
                    {1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0},
                    {1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0},
                    {1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0},
                    {1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0},
                    {1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0},
                    {1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0},
                    {1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0},
                    {1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0}
                }
            };
            // For TCN use first 64 data points to initialize the window
            for (int col = 0; col < TCN_WINDOW_SIZE; col++)
            {
                for (int row = 0; row < INPUT_NUM_PARAMS; row++)
                {
                    // input[0][row][col] = input_data[row][col];
                    input[0][row][col] = input_data[col][row];
                }
                input[0][INPUT_NUM_PARAMS][col] = expected[col][0] / TEMP_SCALE;
                input[0][INPUT_NUM_PARAMS+ 1][col] = expected[col][1] / TEMP_SCALE;
                input[0][INPUT_NUM_PARAMS+ 2][col] = expected[col][2] / TEMP_SCALE;
                input[0][INPUT_NUM_PARAMS+ 3][col] = expected[col][3] / TEMP_SCALE;
            }
            float hidden_state[1][4] = {{1.0,1.0,1.0,1.0}};
            float output[1][4];
        #endif

        // Buffers to hold predicted values
        float predicted_pm[INPUT_DATA_LENGTH];
        float predicted_sy[INPUT_DATA_LENGTH];
        float predicted_st[INPUT_DATA_LENGTH];
        float predicted_sw[INPUT_DATA_LENGTH];
            
        // Copy data from input_data array into the input tensor
        start = now(); // Start timing for total execution

        #if defined(USE_MLP_MODEL) || defined(USE_RNN_MODEL)
            for (int i = 0; i < INPUT_DATA_LENGTH; i++)
            {
                // Data preparation step
                for (int j = 0; j < INPUT_NUM_PARAMS; j++)
                {
                    input[0][0][j] = input_data[i][j];
                }
        #elif defined(USE_TCN_MODEL)
            // For TCN, input window is updated after each inference
            for (int i = TCN_WINDOW_SIZE; i < INPUT_DATA_LENGTH; i++)
            {
                // No data preparation step needed here as input window is managed in the loop
        #endif
            // Time individual inference
            start_single_run = now();
            // Inference step
            #ifdef USE_MLP_MODEL
                entry_mlp(input,hidden_state,output,hidden_state_upd);

            #elif defined(USE_RNN_MODEL)
                entry_rnn(input,hidden_state,cell_state,output);

            #elif defined(USE_TCN_MODEL)
                entry_tcn(input,output);
            #endif

            latency_single_run = elapsed(start_single_run);
            // Accumulate for average calculation
            avg_latency += latency_single_run;
            
            #ifdef USE_TCN_MODEL
            // Store predictions (scale back to original temperature range)
            predicted_pm[i - TCN_WINDOW_SIZE] = output[0][0] * TEMP_SCALE;  // Store the predicted PM temperature
            predicted_sy[i - TCN_WINDOW_SIZE] = output[0][1] * TEMP_SCALE;  // Store the predicted SY temperature
            predicted_st[i - TCN_WINDOW_SIZE] = output[0][2] * TEMP_SCALE;  // Store the predicted ST temperature
            predicted_sw[i - TCN_WINDOW_SIZE] = output[0][3] * TEMP_SCALE;  // Store the predicted SW temperature
            
            #else
            predicted_pm[i] = output[0][0] * TEMP_SCALE;  // Store the predicted PM temperature
            predicted_sy[i] = output[0][1] * TEMP_SCALE;  // Store the predicted SY temperature
            predicted_st[i] = output[0][2] * TEMP_SCALE;  // Store the predicted ST temperature
            predicted_sw[i] = output[0][3] * TEMP_SCALE;  // Store the predicted SW temperature
            #endif

            // Processing for next timestep
            #ifdef USE_MLP_MODEL
                // copy output to hidden_state for next timestep (FIXED SIZE)
                memcpy(hidden_state, output, sizeof(hidden_state));

            #elif defined(USE_RNN_MODEL)
                // For RNN, append previous outputs to input for next timestep
                input[0][0][INPUT_NUM_PARAMS ] = output[0][0];     // PM
                input[0][0][INPUT_NUM_PARAMS + 1] = output[0][1];  // Stator Yoke
                input[0][0][INPUT_NUM_PARAMS + 2] = output[0][2];  // Stator Tooth
                input[0][0][INPUT_NUM_PARAMS + 3] = output[0][3];  // Stator Winding

            #elif defined(USE_TCN_MODEL)
            // For TCN, update the input window by shifting and adding new data
            // Shift window up (drop first row)
             for (int row = 0; row < INPUT_NUM_PARAMS + (TARGET_NUM_PARAMS); row++)
             {
                 for (int col = 0; col < TCN_WINDOW_SIZE - 1  ; col++)
                 {
                     input[0][row][col] = input[0][row][col+1];
                 }
             }
            
            // Add new input to last column of the window
            for (int row = 0; row < INPUT_NUM_PARAMS ; row++)
            {
                input[0][row][TCN_WINDOW_SIZE- 1] = input_data[i][row];
            }
            input[0][INPUT_NUM_PARAMS][TCN_WINDOW_SIZE- 1] = output[0][0];  // PM
            input[0][INPUT_NUM_PARAMS+ 1][TCN_WINDOW_SIZE- 1] = output[0][1];  // PM
            input[0][INPUT_NUM_PARAMS+ 2][TCN_WINDOW_SIZE- 1] = output[0][2];  // PM
            input[0][INPUT_NUM_PARAMS+ 3][TCN_WINDOW_SIZE- 1] = output[0][3];  // PM
            #endif
        }
            
        latency = elapsed(start); // Total time for all inferences
        avg_latency = avg_latency / INPUT_DATA_LENGTH; // Calculate average
        
        delayMs(2000);
        display_ascii_clrscr(DISPLAYSTDOUT0);
        conio_driver.displaymode =DISPLAYGRAPHICS0;
        display_graphics_clrscr(DISPLAYGRAPHICS0);

        for (uint8_t param = 0; param < TARGET_NUM_PARAMS ; param++)
        {
            // Create temporary 1D arrays for the current parameter
            float expected_param[TARGET_DATA_LENGTH];
            float predicted_param[TARGET_DATA_LENGTH];

            // Extract the current parameter column from the 2D arrays
            for (uint16_t i = 0; i < TARGET_DATA_LENGTH; i++)
            {
#ifndef COMPARE_PREDICTED
                expected_param[i] = expected[i][param];
#else
                expected_param[i] = predicted[i][param];
#endif
                predicted_param[i] = predicted[i][param];
            }

            // Draw the graph for this parameter
            // Optional: Add title to indicate which parameter is being displayed
            const char* param_names[] = {"PM", "Stator Yoke", "Stator Tooth", "Stator Winding"};
            display_ascii_printfxy (DISPLAYBAR, 0, 0, (const uint8 *)"Estimated vs Predicted Temperature     ");
            switch (param)
            {
                case 0:
                    draw_graph_borders(DISPLAYGRAPHICS0, PARAM_0);
#ifdef MLP_GRAPH
                    draw_graph(DISPLAYGRAPHICS0, expected_param, predicted_param, TARGET_DATA_LENGTH,(uint8_t*)param_names[param], PARAM_0);
#else
                    draw_graph(DISPLAYGRAPHICS0, expected_param, predicted_pm, TARGET_DATA_LENGTH,(uint8_t*)param_names[param], PARAM_0);
#endif
                    break;

                case 1:
                    draw_graph_borders(DISPLAYGRAPHICS0, PARAM_1);
#ifdef MLP_GRAPH
                    draw_graph(DISPLAYGRAPHICS0, expected_param, predicted_param, TARGET_DATA_LENGTH,(uint8_t*)param_names[param], PARAM_1);
#else
                    draw_graph(DISPLAYGRAPHICS0, expected_param, predicted_sy, TARGET_DATA_LENGTH,(uint8_t*)param_names[param], PARAM_1);
#endif
                    break;

                case 2:
                    draw_graph_borders(DISPLAYGRAPHICS0, PARAM_2);
#ifdef MLP_GRAPH
                    draw_graph(DISPLAYGRAPHICS0, expected_param, predicted_param, TARGET_DATA_LENGTH,(uint8_t*)param_names[param], PARAM_2);
#else
                    draw_graph(DISPLAYGRAPHICS0, expected_param, predicted_st, TARGET_DATA_LENGTH,(uint8_t*)param_names[param], PARAM_2);
#endif
                    break;

                case 3:
                    draw_graph_borders(DISPLAYGRAPHICS0, PARAM_3);
#ifdef MLP_GRAPH
                    draw_graph(DISPLAYGRAPHICS0, expected_param, predicted_param, TARGET_DATA_LENGTH,(uint8_t*)param_names[param], PARAM_3);
#else
                    draw_graph(DISPLAYGRAPHICS0, expected_param, predicted_sw, TARGET_DATA_LENGTH,(uint8_t*)param_names[param], PARAM_3);
#endif
                    break;

                default:
                    break;
            }
            delayMs(5000);
             display_graphics_clrscr(DISPLAYGRAPHICS0);
        }

        // Display results (removed unused snprintf calls)
        conio_driver.displaymode =DISPLAYSTDOUT0;
        display_ascii_clrscr(DISPLAYSTDOUT0);
        display_ascii_printfxy (DISPLAYSTDOUT0, 0, 0, (const uint8 *)"Last Run Latency: %.3f ms", latency_single_run);
        display_ascii_printfxy (DISPLAYSTDOUT0, 0, 1, (const uint8 *)"Avg Latency: %.3f ms", avg_latency);
        display_ascii_printfxy (DISPLAYSTDOUT0, 0, 2, (const uint8 *)"Total Latency: %.3f ms", latency);

        // hidden_state[0][0] = 0.5; hidden_state[0][1] = 0.5; hidden_state[0][2] = 0.5; hidden_state[0][3] = 0.5;
        while(1)
        {
            // for (int i = 0; i < INPUT_DATA_LENGTH; i++)
            // {
            //     for (int j = 0; j < INPUT_NUM_PARAMS; j++)
            //     {
            //         input[0][0][j] = input_data[i][j];
            //     }

            //     entry_mlp(input,hidden_state,output,hidden_state_upd);
            //     // copy output to hidden_state for next timestep (FIXED SIZE)
            //     memcpy(hidden_state, output, sizeof(hidden_state));
            //     for (int k = 0; k < 4; k++)
            //     {
            //         // printf("%f ",output[i][j]);
            //         switch (k)
            //         {
            //             case 0:
            //                 display_graphics_textcolor(DISPLAYSTDOUT0, COLOR_GREEN);
            //                 display_ascii_printfxy(DISPLAYSTDOUT0, 0, k, (const uint8 *)"Estimated PM: %.2f", expected[i][0]);
            //                 display_graphics_textcolor(DISPLAYSTDOUT0, COLOR_RED);
            //                 display_ascii_printfxy(DISPLAYSTDOUT0, 0, k+1, (const uint8 *)"Predicted PM: %.2f", output[0][k] * TEMP_SCALE);
            //                 break;
            //             case 1:
            //                 display_graphics_textcolor(DISPLAYSTDOUT0, COLOR_GREEN);
            //                 display_ascii_printfxy(DISPLAYSTDOUT0, 0, k+1, (const uint8 *)"Estimated Stator yoke: %.2f", expected[i][1]);
            //                 display_graphics_textcolor(DISPLAYSTDOUT0, COLOR_RED);
            //                 display_ascii_printfxy(DISPLAYSTDOUT0, 0, k+2, (const uint8 *)"Predicted Stator yoke: %.2f", output[0][k] * TEMP_SCALE);
            //                 break;
            //             case 2:
            //                 display_graphics_textcolor(DISPLAYSTDOUT0, COLOR_GREEN);
            //                 display_ascii_printfxy(DISPLAYSTDOUT0, 0, k+2, (const uint8 *)"Estimated Stator Tooth: %.2f", expected[i][2]);
            //                 display_graphics_textcolor(DISPLAYSTDOUT0, COLOR_RED);
            //                 display_ascii_printfxy(DISPLAYSTDOUT0, 0, k+3, (const uint8 *)"Predicted Stator Tooth: %.2f", output[0][k] * TEMP_SCALE);
            //                 break;
            //             case 3:
            //                 display_graphics_textcolor(DISPLAYSTDOUT0, COLOR_GREEN);
            //                 display_ascii_printfxy(DISPLAYSTDOUT0, 0, k+3, (const uint8 *)"Estimated Stator Winding: %.2f", expected[i][3]);
            //                 display_graphics_textcolor(DISPLAYSTDOUT0, COLOR_RED);
            //                 display_ascii_printfxy(DISPLAYSTDOUT0, 0, k+4, (const uint8 *)"Predicted Stator Winding: %.2f", output[0][k] * TEMP_SCALE);
            //                 break;
            //             default:
            //                 break;
            //         }
            //     }
            //     delayMs(250);
            // }
            blinkLED();
        }
    }
}

void userIsrSTM0()
{
    /* Set next 1ms scheduler tick alarm */
    IfxStm_increaseCompare(&MODULE_STM0, IfxStm_Comparator_0, IFX_CFG_STM_TICKS_PER_MS);

    /* Increment the ms value */
    g_AppCpu0.TickCount_1ms++;

    /* Enable the global interrupts of this CPU */
    IfxCpu_enableInterrupts();

    /* Return if Safety Kit initialization is not yet finished */
    if(!tft_ready)
    {
        return;
    }

    /* action to do each 1ms */
    /* Execute several periodic tasks implemented and used for Safety Kit */
   runStmIsr(&g_AppCpu0, (IfxCpu_ResourceCpu)IfxCpu_getCoreIndex());
}
