/**********************************************************************************************************************
 * \file Configuration.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef CONFIGURATION_H
#define CONFIGURATION_H
/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/
#include "Ifx_reg.h"
#include "Ifx_Cfg.h"
#include <_PinMap/IfxQspi_PinMap.h>
#include <_PinMap/IfxPort_PinMap.h>
#include <_PinMap/IfxScu_PinMap.h>

#if IFXGTM_REG_H == 1
#include <_PinMap/IfxGtm_PinMap.h>
#endif

/******************************************************************************/
/*-----------------------------------Macros-----------------------------------*/
/******************************************************************************/
#define USE_TFT         1
/* set here the used pins for TFT and TOUCH (QSPI0) */
#define TFT_MAX_BAUDRATE            50000000  // maximum baudrate which is possible to get a small time quantum
#define TFT_SCLK_PIN                IfxQspi0_SCLK_P20_13_OUT
#define TFT_MTSR_PIN                IfxQspi0_MTSR_P20_14_OUT
#define TFT_MRST_PIN                IfxQspi0_MRSTA_P20_12_IN
#define TFT_USE_DMA  // comment line for not using DMA
#define DMA_CH_TFT_TX               TFT_DMA_CH_TXBUFF_TO_TXFIFO
#define DMA_CH_TFT_RX               TFT_DMA_CH_RXBUFF_FROM_RXFIFO
#define TFT_TRANSMIT_CALLBACK       tft_transmit_callback

#define TFT_USE_CHIPSELECT          IfxQspi0_SLSO8_P20_6_OUT
#define TFT_UPDATE_IRQ              MODULE_SRC.GPSR.GPSR[0].SR[0]

#if IFXGTM_REG_H == 1 && RUN_BCKLIGHT
#define BACKGROUND_LIGHT            IfxGtm_TOM1_3_TOUT71_P15_0_OUT
#else
#define BACKGROUND_LIGHT            IfxPort_P15_0           // no timer here, no dimming only on/off possible
#endif

/* LEDs on Application Kit */
#define LED0_PORT                   IfxPort_P13_0
#define LED1_PORT                   IfxPort_P13_1
#define LED2_PORT                   IfxPort_P13_2
#define LED3_PORT                   IfxPort_P13_3

/* set the values for systemtimer */
#define IFX_CFG_STM_TICKS_PER_MS (100000) /**< \brief Number of STM ticks per millisecond */
#define IFX_CFG_STM_TIME_IN_MS      1       /*1 milli second*/
//#define IFX_CFG_STM_TICKS_PER_MS    (IfxStm_getTicksFromMilliseconds(&MODULE_STM0, IFX_CFG_STM_TIME_IN_MS))
/* define the CPU which service the selected peripherals */
#define CPU_WHICH_SERVICE_TFT          0     /**< \brief Define the CPU which service the Tft and touch where functions/variables are located.  */

#define REFRESH_TFT 50      // Refresh rate [ms]; 1x refresh ~0,8 % CPU load; for graphic-out: 4 colors ~ 1.2 % CPU load, 16 colors ~ 0.8 % CPU load
                            // Max refresh rate ~ 40 ms due to QSPI-load
#define BOARD_TEXT          "Project Thesis Azlan Ikram"
/* baord name used on display, here shorted because limited y space in TFT line */
#define BOARD_TEXT_TFT      "TFT_LCD"
#define BOARD_VERSION_TEXT  "V1.0"
#define SW_VERSION_TEXT     "V1 "

#endif
