/**********************************************************************************************************************
 * \file graph_tft.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "graph_tft.h"
#include "conio_tft.h"
#include "IfxStm.h"
#include "conio_cfg.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
static void delayUs(uint32_t us)
{
    IfxStm_waitTicks(&MODULE_STM0,
    IfxStm_getTicksFromMicroseconds(&MODULE_STM0, us));
}

// Map data X value to screen X coordinate
sint32 map_x(float x_data)
{
    float x = GRAPH_X_MIN + ((x_data - DATA_X_MIN) *
             (float)(GRAPH_X_MAX - GRAPH_X_MIN) / (DATA_X_MAX - DATA_X_MIN));
    return (sint32)(x + 0.5f);
}

// Map data Y value to screen Y coordinate
sint32 map_y(float y_data, GraphParam_t param)
{
    float DATA_Y_MIN,DATA_Y_MAX;
    switch (param)
    {
        case PARAM_0:
            DATA_Y_MIN = DATA0_Y_MIN;
            DATA_Y_MAX = DATA0_Y_MAX;
            break;
        case PARAM_1:
            DATA_Y_MIN = DATA1_Y_MIN;
            DATA_Y_MAX = DATA1_Y_MAX;
            break;

        case PARAM_2:
            DATA_Y_MIN = DATA2_Y_MIN;
            DATA_Y_MAX = DATA2_Y_MAX;
            break;

        case PARAM_3:
            DATA_Y_MIN = DATA3_Y_MIN;
            DATA_Y_MAX = DATA3_Y_MAX;
            break;

        default:
            break;
    }
    float y = GRAPH_Y_MIN + ((y_data - DATA_Y_MIN) *
                 (float)(GRAPH_Y_MAX - GRAPH_Y_MIN) / (DATA_Y_MAX - DATA_Y_MIN));
        return (sint32)(y + 0.5f);
}

// --- Main graph drawing ---
void draw_graph(TDISPLAYMODE displaymode,const float *ground_truth, const float *predicted, int num_samples, uint8_t *param_names, GraphParam_t param)
{
    int i;
    sint32 x1, y1, x2, y2;

    display_graphics_textcolor(displaymode, COLOR_WHITE);
    display_graphics_printfxy(displaymode, ((GRAPH_X_MIN + GRAPH_X_MAX)/2) - 50, GRAPH_Y_MAX - 6 ,(uint8_t*)param_names);
    int step = num_samples / GRAPH_X_LEN;
    if (step < 1) step = 1;
    // Optional: legend  for Ground Truth
    display_graphics_textcolor(displaymode, COLOR_GREEN);
    display_graphics_printfxy(displaymode, GRAPH_X_MIN + 15, GRAPH_Y_MAX - 20,(uint8*)"Ground Truth");
    for (i = 0; i < num_samples - step; i += step)
    {
        x1 = map_x(i);
        y1 = map_y(ground_truth[i], param);
        x2 = map_x(i + step);
        y2 = map_y(ground_truth[i + step], param);
        display_graphics_line(displaymode, x1, y1, x2, y2, COLOR_GREEN);
        // synchronization delay
        delayUs(100);
    }

    // Optional: legend  for Predicted
    display_graphics_textcolor(displaymode, COLOR_RED);
    display_graphics_printfxy(displaymode, GRAPH_X_MIN + 15, GRAPH_Y_MAX - 32,(uint8*)"Predicted");
    // Draw predicted line (e.g., color 1 = red)
    for (i = 0; i < num_samples - step; i += step)
    {
        x1 = map_x(i);
        y1 = map_y(predicted[i], param);
        x2 = map_x(i + 1);
        y2 = map_y(predicted[i + 1], param);
        display_graphics_line(displaymode, x1, y1, x2, y2, COLOR_RED);
        // synchronization delay
        delayUs(100);
    }


    display_graphics_textcolor(displaymode, COLOR_WHITE);
}

void draw_graph_borders(TDISPLAYMODE displaymode, GraphParam_t param)
{
    float DATA_Y_MIN, DATA_Y_MAX, DATA_Y_STEP;
    switch (param)
    {
        case PARAM_0:
            DATA_Y_MIN = DATA0_Y_MIN;
            DATA_Y_MAX = DATA0_Y_MAX;
            DATA_Y_STEP = DATA0_Y_STEP;
            break;
        case PARAM_1:
            DATA_Y_MIN = DATA1_Y_MIN;
            DATA_Y_MAX = DATA1_Y_MAX;
            DATA_Y_STEP = DATA1_Y_STEP;
            break;
        case PARAM_2:
            DATA_Y_MIN = DATA2_Y_MIN;
            DATA_Y_MAX = DATA2_Y_MAX;
            DATA_Y_STEP = DATA2_Y_STEP;
            break;
        case PARAM_3:
            DATA_Y_MIN = DATA3_Y_MIN;
            DATA_Y_MAX = DATA3_Y_MAX;
            DATA_Y_STEP = DATA3_Y_STEP;
            break;
        default:
            break;
    }

    display_graphics_line (displaymode, GRAPH_X_MIN, GRAPH_Y_MIN, GRAPH_X_MAX, GRAPH_Y_MIN, COLOR_WHITE);
    display_graphics_line (displaymode, GRAPH_X_MAX, GRAPH_Y_MIN, GRAPH_X_MAX, GRAPH_Y_MAX, COLOR_WHITE);
    display_graphics_line (displaymode, GRAPH_X_MAX, GRAPH_Y_MAX, GRAPH_X_MIN, GRAPH_Y_MAX, COLOR_WHITE);
    display_graphics_line (displaymode, GRAPH_X_MIN, GRAPH_Y_MAX, GRAPH_X_MIN, GRAPH_Y_MIN, COLOR_WHITE);

    //Draw y-axis graph markings
    display_graphics_line (displaymode, GRAPH_X_MIN, (GRAPH_Y_MIN + ((GRAPH_Y_LEN)/4)) , GRAPH_X_MIN - 4, (GRAPH_Y_MIN + ((GRAPH_Y_LEN)/4)) , COLOR_WHITE);
    display_graphics_line (displaymode, GRAPH_X_MIN, (GRAPH_Y_MIN + ((GRAPH_Y_LEN)/2)), GRAPH_X_MIN-4, (GRAPH_Y_MIN + ((GRAPH_Y_LEN)/2)), COLOR_WHITE);
    display_graphics_line (displaymode, GRAPH_X_MIN, (GRAPH_Y_MIN + ((GRAPH_Y_LEN)*3/4)), GRAPH_X_MIN-4, (GRAPH_Y_MIN + ((GRAPH_Y_LEN)*3/4)), COLOR_WHITE);

    //print y axis text
    display_graphics_printfxy(displaymode, 0, GRAPH_Y_MIN,(uint8*)"%.1f", DATA_Y_MIN);
    display_graphics_printfxy(displaymode, 0, (GRAPH_Y_MIN + ((GRAPH_Y_LEN)/4)),(uint8*)"%.1f", (DATA_Y_MIN + DATA_Y_STEP));
    display_graphics_printfxy(displaymode, 0, (GRAPH_Y_MIN + ((GRAPH_Y_LEN)/2)),(uint8*)"%.1f", (DATA_Y_MIN + 2 * DATA_Y_STEP));
    display_graphics_printfxy(displaymode, 0, (GRAPH_Y_MIN + ((GRAPH_Y_LEN)*3/4)),(uint8*)"%.1f", (DATA_Y_MIN + 3 * DATA_Y_STEP));
    display_graphics_printfxy(displaymode, 0, GRAPH_Y_MAX - 18,(uint8*)"%.1f", DATA_Y_MAX);
    display_graphics_printfxy(displaymode, 0, GRAPH_Y_MAX-6,(uint8*)"Temp C");

    //Draw x-axis graph markings
    display_graphics_line (displaymode, (GRAPH_X_MIN + ((GRAPH_X_LEN)/4)), GRAPH_Y_MIN , (GRAPH_X_MIN + ((GRAPH_X_LEN)/4)), GRAPH_Y_MIN - 4 , COLOR_WHITE);
    display_graphics_line (displaymode, (GRAPH_X_MIN + ((GRAPH_X_LEN)/2)), GRAPH_Y_MIN, (GRAPH_X_MIN + ((GRAPH_X_LEN)/2)), GRAPH_Y_MIN - 4, COLOR_WHITE);
    display_graphics_line (displaymode, (GRAPH_X_MIN + ((GRAPH_X_LEN)*3/4)), GRAPH_Y_MIN, (GRAPH_X_MIN + ((GRAPH_X_LEN)*3/4)), GRAPH_Y_MIN - 4, COLOR_WHITE);

    //print x axis text
    display_graphics_printfxy(displaymode, GRAPH_X_MIN, GRAPH_Y_MIN - 20,(uint8*)"%d", DATA_X_MIN);
    display_graphics_printfxy(displaymode, (GRAPH_X_MIN + ((GRAPH_X_LEN)/4)), GRAPH_Y_MIN - 20,(uint8*)"%d", (DATA_X_MIN + DATA_X_STEP));
    display_graphics_printfxy(displaymode, (GRAPH_X_MIN + ((GRAPH_X_LEN)/2)), GRAPH_Y_MIN - 20,(uint8*)"%d", (DATA_X_MIN + 2 * DATA_X_STEP));
    display_graphics_printfxy(displaymode, (GRAPH_X_MIN + ((GRAPH_X_LEN)*3/4)), GRAPH_Y_MIN - 20,(uint8*)"%d", (DATA_X_MIN + 3 * DATA_X_STEP));
    display_graphics_printfxy(displaymode, GRAPH_X_MAX-12, GRAPH_Y_MIN - 20,(uint8*)"%d", DATA_X_MAX);
    display_graphics_printfxy(displaymode, ((GRAPH_X_MIN + GRAPH_X_MAX)/2) - 50, GRAPH_Y_MIN - 32,(uint8*)"No of Samples");
}
