/**********************************************************************************************************************
 * \file graph_tft.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef TFT_GRAPH_TFT_H_
#define TFT_GRAPH_TFT_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "conio_cfg.h"
#include "stdint.h"
#include "./prediction_data/predicted_vs_expected_all_params_4000_profile60_DenseMLP.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/
typedef enum 
{
    PARAM_0 = 0,
    PARAM_1,
    PARAM_2,
    PARAM_3
} GraphParam_t;

// Graph area (example: leave some margins)
#define GRAPH_X_MIN   40
#define GRAPH_X_MAX   300
#define GRAPH_X_LEN   GRAPH_X_MAX - GRAPH_X_MIN
#define GRAPH_Y_MIN   40
#define GRAPH_Y_MAX   220
#define GRAPH_Y_LEN   GRAPH_Y_MAX - GRAPH_Y_MIN

#define DATA_X_MIN    0
#define DATA_X_MAX    TARGET_DATA_LENGTH
#define DATA_X_STEP   ((DATA_X_MAX - DATA_X_MIN)/4)

#define DATA0_Y_MIN    (TARGET_PARAM_0_MIN - (0.1 * TARGET_PARAM_0_MAX))
#define DATA0_Y_MAX    (TARGET_PARAM_0_MAX + (0.1 * TARGET_PARAM_0_MAX))
#define DATA0_Y_STEP   ((DATA0_Y_MAX - DATA0_Y_MIN)/4)

#define DATA1_Y_MIN    (TARGET_PARAM_1_MIN - (0.1 * TARGET_PARAM_1_MAX))
#define DATA1_Y_MAX    (TARGET_PARAM_1_MAX + (0.1 * TARGET_PARAM_1_MAX))
#define DATA1_Y_STEP   ((DATA1_Y_MAX - DATA1_Y_MIN)/4)

#define DATA2_Y_MIN    (TARGET_PARAM_2_MIN - (0.1 * TARGET_PARAM_2_MAX))
#define DATA2_Y_MAX    (TARGET_PARAM_2_MAX + (0.1 * TARGET_PARAM_2_MAX))
#define DATA2_Y_STEP   ((DATA2_Y_MAX - DATA2_Y_MIN)/4)

#define DATA3_Y_MIN    (TARGET_PARAM_3_MIN - (0.1 * TARGET_PARAM_3_MAX))
#define DATA3_Y_MAX    (TARGET_PARAM_3_MAX + (0.1 * TARGET_PARAM_3_MAX))
#define DATA3_Y_STEP   ((DATA3_Y_MAX - DATA3_Y_MIN)/4)
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
void draw_graph_borders(TDISPLAYMODE displaymode, GraphParam_t param);
void draw_graph(TDISPLAYMODE displaymode,const float *ground_truth, const float *predicted, int num_samples, uint8_t *param_names,  GraphParam_t param);
sint32 map_x(float x_data);
sint32 map_y(float y_data, GraphParam_t param);
static void delayUs(uint32_t us);
#endif /* TFT_GRAPH_TFT_H_ */
