/**********************************************************************************************************************
 * \file tft_app.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "configuration.h"
#include "configurationIsr.h"
#include "tfthw.h"
#include "tft/conio_tft.h"
#include "DrawLogo.h"
#include "tft_app.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
volatile boolean tft_ready = 0;
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/
typedef uint8 TDISPLAY_GRAPHICS0[GRAPHICSWIDTH/2];      //16 color
TDISPLAY_GRAPHICS0 display_graphics0 IFX_ALIGN(4);
TDISPLAY display_stdout0 IFX_ALIGN(4);
TDISPLAYCOLOR displaycolor_stdout0 IFX_ALIGN(4);
TDISPLAY display_stdout1 IFX_ALIGN(4);
TDISPLAYCOLOR displaycolor_stdout1 IFX_ALIGN(4);
TDISPLAYBAR display_bar IFX_ALIGN(4);
TDISPLAYBARCOLOR displaycolor_bar IFX_ALIGN(4);
TDISPLAY display_menu IFX_ALIGN(4);
TDISPLAYCOLOR displaycolor_menu IFX_ALIGN(4);

const TCONIODMENTRY conio_displaymode_list[CONIO_MAXDISPLAYS] =
{
    { DISPLAYBAR, {(uint8 *) & display_bar, (uint8 *) & displaycolor_bar, TEXTMODE, COLOR_WHITE, TERMINAL_MAXX, 1, 0, 0} },
    { DISPLAYMENU, {(uint8 *) & display_menu, (uint8 *) & displaycolor_menu, TEXTMODE, COLOR_WHITE, TERMINAL_MAXX, TERMINAL_MAXY-1, 0, 0} },
    { DISPLAYSTDOUT0, {(uint8 *) & display_stdout0, (uint8 *) & displaycolor_stdout0, TEXTMODE, COLOR_WHITE, TERMINAL_MAXX, TERMINAL_MAXY-1, 0, 0} },
    { DISPLAYSTDOUT1, {(uint8 *) & display_stdout1, (uint8 *) & displaycolor_stdout1, TEXTMODE, COLOR_WHITE, TERMINAL_MAXX, TERMINAL_MAXY-1, 0, 0} },
    { DISPLAYGRAPHICS0, {(uint8 *) & display_graphics0, 0, GRAPHICMODE_16COLOR, COLOR_WHITE, TERMINAL_MAXX, TERMINAL_MAXY, 0, 0} }
};
/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
void initPins(void)
{
    /* CS to TFT */
    IfxPort_setPinModeInput(TFT_USE_CHIPSELECT.pin.port, TFT_USE_CHIPSELECT.pin.pinIndex, IfxPort_InputMode_pullUp);
}

void tft_app_init(IfxCpu_ResourceCpu cpuIndex)
{
    if(cpuIndex == IfxCpu_ResourceCpu_0)
    {
        initPins();
    }

    if (CPU_WHICH_SERVICE_TFT)
        IfxSrc_init(&TFT_UPDATE_IRQ, (IfxSrc_Tos)(CPU_WHICH_SERVICE_TFT+1), ISR_PRIORITY_CPUSRV0);
    else
        IfxSrc_init(&TFT_UPDATE_IRQ, (IfxSrc_Tos)CPU_WHICH_SERVICE_TFT, ISR_PRIORITY_CPUSRV0);
    IfxSrc_enable(&TFT_UPDATE_IRQ);

    tft_init();
    conio_init ((pTCONIODMENTRY)conio_displaymode_list);
    tft_ready = TRUE;
    conio_driver.displaymode =DISPLAYGRAPHICS0;
    graph_drawInfineonLogo();
}

IFX_INTERRUPT (cpu_service0Irq, CPU_WHICH_SERVICE_TFT, ISR_PRIORITY_CPUSRV0)
{
    __enable();
    if (tft_ready == 0)
    {
        return;
    }
    conio_periodic ();
}

void runStmIsr(App_Cpu *lcl_AppCpu, IfxCpu_ResourceCpu cpuIndex)
{
    /* action to do each 1ms */
#if USE_TFT
    if(CPU_WHICH_SERVICE_TFT == cpuIndex)
    {
        /* action to do each REFRESH_TFT ms */
        if ((lcl_AppCpu->TickCount_1ms % REFRESH_TFT) == 0)
        {
            IfxSrc_setRequest(&TFT_UPDATE_IRQ);    //trigger the tft lib
        }
    }/* CPU_WHICH_SERVICE_TFT */
#endif /* USE_TFT */

    /* action to do each 10ms */
    if ((lcl_AppCpu->TickCount_1ms % 10) == 0)
    {

    }
    /* action to do each 100ms */
    if ((lcl_AppCpu->TickCount_1ms % 100) == 0)
    {

    }
}
